name: test actions
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4
      - name: install deps
        run: yarn install
      - name: build
        run: yarn build
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: dist
          name: build
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-files
