name: test actions
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4
      - name: install deps
        run: yarn install
      - name: linter
        run: yarn lint
      - name: build
        run: yarn build
